### ISSUE TITLE
When merging to an existing rule, no properties should be overwritten

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/crbuilder#2]
Example
UID: 0066ab1c-982c-42e6-96f8-e7cbec162a91

In prod, the outcome is:
```yaml
Outcome:
  Message: USUBJID is not unique within study
  Output Variables:
    - USUBJID
```

In dev, the outcome is overwritten:
```yaml
Outcome:
  Message: ' and USUBJID unique within a submission'
```
