### ISSUE TITLE
Scope being overwritten

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/crbuilder#6]
ID: 07bf0e3a-e2db-4887-b843-ef8b48b58934
Rule Id: CG0143

Prod Scope:
```yaml
Scope:
  Classes:
    Include:
      - EVENTS
  Domains:
    Include:
      - DS
```

Generated Scope:
```yaml
Scope:
  Classes:
    Include:
      - SPECIAL PURPOSE
  Domains:
    Include:
      - DM
```

Again, no properties should be overwritten. The merge should only do additions, not replaces. For this case, where the scopes don't match what is expected, this should appear in the merge log file for manual investigation.
